apiVersion: v1
kind: Service
metadata:
  annotations:
    # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: node-elb
  labels:
    k8s-app: nodejs
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
  selector:
    k8s-app: nodejs