apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: node-application-memory-scaling
  namespace: production
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-server
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50